server:
  port: ${SERVER_PORT:8090}

spring:
  application:
    name: ms-video
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://root:password@localhost:27017/msvideo?authSource=admin}
      database: ${MONGO_DATABASE:msvideo}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10GB
      max-request-size: 10GB
  cloud:
    aws:
      region:
        static: ${AWS_REGION:us-east-1}
    sqs:
      queues:
        video-process-event: ${SPRING_CLOUD_SQS_QUEUES_VIDEO_PROCESS_EVENT:video-processed-event}
        video-process-command: ${SPRING_CLOUD_SQS_QUEUES_VIDEO_PROCESS_COMMAND:video-process-command}
        video-updated-event: ${SPRING_CLOUD_SQS_QUEUES_VIDEO_UPDATED_EVENT:video-updated-event}
    s3:
      bucket-name: ${SPRING_CLOUD_S3_BUCKET_NAME:msvideo-bucket}
      input-prefix: ${SPRING_CLOUD_S3_INPUT_PREFIX:video-input-storage/}
